services:
  app:
    build: .
    command: uv run manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - app-db
      - redis
  app-db:
    image: postgres:16
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: django-db
  redis:
    image: redis:8-alpine
  svelte:
    image: node:25
    working_dir: /app/svelte
    volumes:
      - .:/app
    ports:
      - "5173:5173"